# Generated by Django 5.0.4 on 2024-04-16 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_title_todo_item_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_item',
            name='completed',
        ),
    ]
